import js from "@eslint/js";

export default [
  js.configs.recommended,
  // Main source files
  {
    files: ["src/**/*.js"],
    ignores: ["src/**/__tests__/**"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Scriptable globals
        config: "readonly",
        args: "readonly",
        Script: "readonly",
        FileManager: "readonly",
        Request: "readonly",
        ListWidget: "readonly",
        Color: "readonly",
        Font: "readonly",
        Size: "readonly",
        Point: "readonly",
        Rect: "readonly",
        DrawContext: "readonly",
        Path: "readonly",
        UITable: "readonly",
        UITableRow: "readonly",
        UITableCell: "readonly",
        Alert: "readonly",
        Safari: "readonly",
        WebView: "readonly",
        QuickLook: "readonly",
        DocumentPicker: "readonly",
        Data: "readonly",
        Image: "readonly",
        Photos: "readonly",
        Pasteboard: "readonly",
        Notification: "readonly",
        Timer: "readonly",
        Device: "readonly",
        Calendar: "readonly",
        CalendarEvent: "readonly",
        Reminder: "readonly",
        Contact: "readonly",
        ContactsContainer: "readonly",
        ContactsGroup: "readonly",
        Location: "readonly",
        Message: "readonly",
        Mail: "readonly",
        CallbackURL: "readonly",
        Keychain: "readonly",
        importModule: "readonly",
        module: "readonly",
        log: "readonly",
        logError: "readonly",
        logWarning: "readonly",
        // Node.js globals
        console: "readonly",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Buffer: "readonly",
        // Common globals
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        Object: "readonly",
        Array: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        // Cross-module globals (available after build concatenation)
        // From config.js
        isDevelopment: "readonly",
        getFileManager: "readonly",
        getDataPath: "readonly",
        getTransactionsPath: "readonly",
        getPricesPath: "readonly",
        ensureDataDirectory: "readonly",
        // From formatters.js
        COLORS: "readonly",
        formatNumber: "readonly",
        formatPercent: "readonly",
        formatCurrency: "readonly",
        padLeft: "readonly",
        padRight: "readonly",
        getChangeColor: "readonly",
        getCurrencyFromSymbol: "readonly",
        // From data-loader.js
        readHoldings: "readonly",
        readTransactions: "readonly",
        readPriceCache: "readonly",
        writePriceCache: "readonly",
        readIncomeWidgetState: "readonly",
        writeIncomeWidgetState: "readonly",
        readPrices: "readonly",
        getLatestPrice: "readonly",
        appendPrices: "readonly",
        // From api-client.js
        fetchStockPrice: "readonly",
        fetchHistoricalPrices: "readonly",
        fetchEURRate: "readonly",
        fetchMultipleStockPricesBatched: "readonly",
        fetchMultipleHistoricalBatched: "readonly",
        fetchMultipleEURRates: "readonly",
        // From calculations.js
        calculatePortfolioValue: "readonly",
        calculateHistoricalValues: "readonly",
        calculateMonthlyPL: "readonly",
        calculateStockAttribution: "readonly",
        getYearsFromTransactions: "readonly",
        calculatePortfolio: "readonly",
        getHistoricalPortfolioValues: "readonly",
        // From chart-renderer.js
        drawChart: "readonly",
        drawBarChart: "readonly",
        drawGraph: "readonly",
        // From ui-components.js
        createLargeWidget: "readonly",
        createSmallWidget: "readonly",
        createIncomeLargeWidget: "readonly",
        createIncomeSmallWidget: "readonly",
        showInteractiveMenu: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-console": "off",
      "no-redeclare": "warn",
      "semi": ["error", "always"],
      "quotes": ["warn", "single", { avoidEscape: true }],
    },
  },
  // Test files
  {
    files: ["src/**/__tests__/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Jest globals
        describe: "readonly",
        test: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        jest: "readonly",
        // Node globals
        console: "readonly",
        process: "readonly",
        globalThis: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "semi": ["error", "always"],
      "quotes": ["warn", "single", { avoidEscape: true }],
    },
  },
  {
    ignores: ["dist/**", "node_modules/**", "*.config.js", "build.js"],
  },
];
